sf_opportunity_history_unioned:
    constraints:
        unique:
            - opportunity_history_id
        not_null:
            - opportunity_history_id
            - created_date
            - created_by_id

sf_opportunity_history_joined:
    constraints:
        unique:
            - opportunity_history_id
        not_null:
            - opportunity_history_id

sf_opportunity_history_daily:
    constraints:
        unique:
            - id
        not_null:
            - id

sf_opportunity_history_monthly:
    constraints:
        unique:
            - id
        not_null:
            - id
