name: 'salesforce'
version: '1.0'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  salesforce:
      enabled: true
      materialized: ephemeral
      vars:
        schema: 'salesforce_s'
        first_record:               # earliest date in opportunity history
        opportunity_history_custom_fields:
        #    - 'example_field'
