name: 'salesforce'
version: '1.0'

profile: 'knotel'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

repositories:
    - https://github.com/fishtown-analytics/dbt-utils.git@0.1.6

models:
  salesforce:
      enabled: true
      materialized: view
      vars:
        sf_account:                 salesforce.account
        sf_contact:                 salesforce.contact
        sf_lead:                    salesforce.lead
        sf_opportunity:             salesforce.opportunity
        sf_opportunity_history:     salesforce.opportunityhistory
        sf_user:                    salesforce.user
        first_record:               '2017-07-26'
