name: 'salesforce'
version: '1.0'

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

on-run-start: "alter session set quoted_identifiers_ignore_case = false" # snowflake

repositories:
    - https://github.com/fishtown-analytics/dbt-utils.git@0.1.6

models:
  salesforce:
      enabled: true
      materialized: view
      vars:
        sf_account:                 #"schema.table"
        sf_contact:                 #"schema.table"
        sf_lead:                    #"schema.table"
        sf_opportunity:             #"schema.table"
        sf_opportunity_history:     #"schema.table"
        sf_user:                    #"schema.table"
        first_record:               # earliest date in opportunity history
